name: omonie
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  socket_io_client: ^2.0.3+1
  provider: ^6.1.1
  dio: ^5.4.0
  google_fonts: ^6.1.0
  sizer: ^2.0.15
  flutter_svg: ^2.0.9
  flutter_date_pickers: ^0.4.2
  flutter_otp_text_field: ^1.1.1
  flutter_material_color_picker: ^1.2.0
  fl_country_code_picker: ^0.1.9+1
  http: ^1.1.0
  intl: ^0.18.0
  shared_preferences: ^2.2.2
  jwt_decoder: ^2.0.1
  flutter_paystack_payment_plus: ^0.0.4
  gif: ^2.3.0
  cached_network_image: ^3.3.1
  file_picker: ^5.3.1
  material_tag_editor: ^0.1.2
  timeago: ^3.6.1
  path: ^1.8.3
  dropdown_button2: ^2.3.9
  keyboard_dismisser: ^3.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

dependency_overrides:
  http: ^0.13.5


flutter:
  uses-material-design: true


  assets:
    - assets/images/.
    - assets/icons/.

flutter_assets:
  assets_path: assets/
  output_path: lib/src/constants/
  filename: assets.dart